# Generated by Django 6.1.1 on 2026-10-04 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='events/')),
                ('attendees', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='FeatureStrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=80)),
                ('icon', models.CharField(default='heart', max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('F', 'Woman'), ('M', 'Man')], max_length=1)),
                ('city', models.CharField(max_length=60)),
                ('occupation', models.CharField(max_length=80)),
                ('intention', models.CharField(default='Marriage-oriented', max_length=60)),
                ('religion', models.CharField(default='Islam', max_length=30)),
                ('photo', models.ImageField(blank=True, upload_to='members/')),
                ('verified', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('compatibility', models.PositiveSmallIntegerField(default=80)),
                ('joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PremiumPerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(unique=True)),
                ('blurb', models.CharField(max_length=80)),
                ('image', models.ImageField(blank=True, upload_to='services/')),
                ('button_label', models.CharField(default='View Advert', max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Service categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='Nusrah', max_length=50)),
                ('tagline', models.CharField(default='People • Values • Marriage', max_length=100)),
                ('hero_title_1', models.CharField(default='Find Someone Special.', max_length=100)),
                ('hero_title_2', models.CharField(default='Build a Marriage.', max_length=100)),
                ('hero_text', models.CharField(default='Connect with verified people who are looking for meaningful relationships and marriage.', max_length=250)),
                ('hero_quote', models.CharField(default='More than a date. A path to a brighter tomorrow.', max_length=200)),
                ('hero_image', models.ImageField(blank=True, upload_to='site/')),
                ('logo', models.ImageField(blank=True, upload_to='site/')),
                ('currency', models.CharField(default='TSh', max_length=10)),
            ],
            options={
                'verbose_name': 'Site setting',
            },
        ),
    ]
