# Generated by Django 6.1.2 on 2026-10-06 21:27

from django.db import migrations, models


OLD = {"brand": "Nusrah", "tagline": "People • Values • Marriage", "hero_quote": "More than a date. A path to a brighter tomorrow."}
NEW = {"brand": "Sakinah", "tagline": "Imani • Mapenzi • Ndoa", "hero_quote": "Zaidi ya uchumba, ni safari ya maisha na mwenye kheri."}


def rebrand(apps, schema_editor):
    """Move settings rows still on the old Nusrah defaults to the Sakinah ones; edited values are left alone."""
    for field, old in OLD.items():
        apps.get_model("core", "SiteSetting").objects.filter(**{field: old}).update(**{field: NEW[field]})
    strip = apps.get_model("core", "FeatureStrip").objects
    strip.filter(icon="cal").update(icon="cal-g")
    strip.filter(icon="shield").update(icon="shield-c")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_member_options_member_bio_member_user_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="advert_image",
            field=models.ImageField(
                blank=True,
                help_text="Photo on the Advertise Your Marriage Service card",
                upload_to="site/",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="premium_image",
            field=models.ImageField(
                blank=True,
                help_text="Couple photo on the Go Premium card",
                upload_to="site/",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="brand",
            field=models.CharField(default="Sakinah", max_length=50),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="hero_quote",
            field=models.CharField(
                default="Zaidi ya uchumba, ni safari ya maisha na mwenye kheri.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="tagline",
            field=models.CharField(default="Imani • Mapenzi • Ndoa", max_length=100),
        ),
        migrations.RunPython(rebrand, migrations.RunPython.noop),
    ]
