# Generated by Django 6.1.2 on 2026-10-06 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sakinah_branding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="education",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="member",
            name="goal",
            field=models.CharField(
                blank=True,
                help_text="Lengo. Leave blank for the default text.",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("single", "Single"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                ],
                default="single",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="origin",
            field=models.CharField(default="Mtanzania", max_length=40),
        ),
        migrations.AddField(
            model_name="member",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="WhatsApp number with country code, e.g. 255712345678",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="whatsapp_ok",
            field=models.BooleanField(
                default=False, verbose_name="Allow WhatsApp messages"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="religion",
            field=models.CharField(
                choices=[("Islam", "Muislamu"), ("Christian", "Mkristo")],
                default="Islam",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="MemberPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="members/")),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="core.member",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(max_length=1000)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("read", models.BooleanField(default=False)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbox",
                        to="core.member",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
    ]
