# Generated by Django 6.1.2 on 2026-10-07 01:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_member_details_photos_messages"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("slug", models.SlugField(unique=True)),
                ("icon", models.CharField(default="book", max_length=30)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Article categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("slug", models.SlugField(unique=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Event categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("logo", models.ImageField(blank=True, upload_to="vendors/")),
                ("city", models.CharField(max_length=60)),
                ("verified", models.BooleanField(default=False)),
                ("member_since", models.DateField(default=django.utils.timezone.now)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "why_choose",
                    models.TextField(blank=True, help_text="One reason per line."),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="about_family",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="member",
            name="body_type",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="member",
            name="drinks",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="exercise",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="member",
            name="family_location",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="member",
            name="family_type",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="member",
            name="father_status",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="member",
            name="food_preference",
            field=models.CharField(blank=True, default="Halal", max_length=60),
        ),
        migrations.AddField(
            model_name="member",
            name="height_cm",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Height (cm)"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="hijab",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="Hijab / dress"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="hobbies",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="member",
            name="income_range",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="member",
            name="languages",
            field=models.CharField(
                blank=True, default="Swahili, English", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="mother_status",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="member",
            name="prayer",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="member",
            name="pref_age_max",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Preferred age to"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="pref_age_min",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Preferred age from"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="pref_education",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Preferred education"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="pref_location",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Preferred location"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="pref_marital",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="Preferred marital status"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="pref_more",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Additional preferences"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="pref_occupation",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Preferred occupation"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="pref_prayer",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Preferred prayer habit"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="pref_relocate",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="Partner willing to relocate"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="pref_values",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Preferred values"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="quran_reading",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="Qur'an / scripture reading"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="siblings",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Number of siblings"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="smokes",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="values",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="member",
            name="willing_to_relocate",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="member",
            name="workplace",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="plan",
            name="features",
            field=models.TextField(
                blank=True,
                help_text="One feature per line. Start a line with - for a feature the plan does not include.",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="icon",
            field=models.ImageField(blank=True, upload_to="plans/"),
        ),
        migrations.AddField(
            model_name="plan",
            name="period",
            field=models.CharField(default="per month", max_length=30),
        ),
        migrations.AddField(
            model_name="plan",
            name="popular",
            field=models.BooleanField(default=False, verbose_name="Most popular"),
        ),
        migrations.AddField(
            model_name="plan",
            name="tagline",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="contact_whatsapp",
            field=models.CharField(
                blank=True,
                help_text="WhatsApp number with country code, e.g. 255712345678",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="offer_text",
            field=models.CharField(
                blank=True,
                help_text="Premium page special offer. Leave blank to hide the offer.",
                max_length=160,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="attendees",
            field=models.PositiveIntegerField(
                default=0,
                help_text="People already going before online registration (e.g. walk-ins).",
            ),
        ),
        migrations.CreateModel(
            name="Advert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                ("city", models.CharField(max_length=60)),
                ("image", models.ImageField(blank=True, upload_to="adverts/")),
                ("price", models.PositiveIntegerField(default=0)),
                (
                    "price_unit",
                    models.CharField(default="Per Event / Day", max_length=40),
                ),
                ("negotiable", models.BooleanField(default=False)),
                ("featured", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                (
                    "highlights",
                    models.TextField(
                        blank=True,
                        help_text="One per line as icon|text, e.g. people|Up to 300 Guests. Icons: people, parking, snow, food, camera, star.",
                    ),
                ),
                (
                    "includes",
                    models.TextField(
                        blank=True, help_text="Package includes, one per line."
                    ),
                ),
                (
                    "extras",
                    models.TextField(
                        blank=True,
                        help_text="Optional additional services, one per line.",
                    ),
                ),
                ("availability", models.CharField(blank=True, max_length=200)),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Extra details, one per line as Label|Value.",
                    ),
                ),
                (
                    "map_query",
                    models.CharField(
                        blank=True,
                        help_text="Address used for the map, e.g. Kariakoo, Dar es Salaam",
                        max_length=160,
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adverts",
                        to="core.servicecategory",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adverts",
                        to="core.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-featured", "-created"],
            },
        ),
        migrations.CreateModel(
            name="AdvertPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="adverts/")),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "advert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="core.advert",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("author", models.CharField(default="Sakinah Team", max_length=80)),
                ("image", models.ImageField(blank=True, upload_to="articles/")),
                ("excerpt", models.CharField(max_length=240)),
                ("body", models.TextField()),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma separated, e.g. Nikah, Communication",
                        max_length=200,
                    ),
                ),
                ("published", models.DateField(default=django.utils.timezone.now)),
                ("featured", models.BooleanField(default=False)),
                ("views", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="core.articlecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-published", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="ArticleComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(max_length=1000)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="core.eventcategory",
            ),
        ),
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("availability", "Check availability"),
                            ("inquiry", "Inquiry"),
                        ],
                        default="inquiry",
                        max_length=12,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("phone", models.CharField(max_length=20)),
                ("event_date", models.DateField(blank=True, null=True)),
                ("guests", models.PositiveIntegerField(blank=True, null=True)),
                ("message", models.TextField(blank=True, max_length=1000)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("handled", models.BooleanField(default=False)),
                (
                    "advert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to="core.advert",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inquiries",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("fake", "Fake profile"),
                            ("rude", "Rude or offensive"),
                            ("scam", "Scam or asking for money"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("details", models.TextField(blank=True, max_length=1000)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="core.member",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdvertReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("comment", models.TextField(blank=True, max_length=1000)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "advert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="core.advert",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advert_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("advert", "user"), name="unique_advert_review"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="core.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "user"), name="unique_event_registration"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Shortlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shortlisted_by",
                        to="core.member",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shortlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "member"), name="unique_shortlist"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "advert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlisted_by",
                        to="core.advert",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "advert"), name="unique_wishlist"
                    )
                ],
            },
        ),
    ]
