# Generated by Django 6.1.2 on 2026-10-07 01:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_profiles_vendors_articles_events"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, max_length=140)),
                ("subject", models.CharField(max_length=150)),
                (
                    "body",
                    models.TextField(
                        help_text="You can use {name} for the member's name."
                    ),
                ),
                ("icon", models.CharField(default="mail", max_length=30)),
                ("color", models.CharField(default="#2546a8", max_length=10)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
        migrations.AddField(
            model_name="member",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="core.plan",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="premium_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("inapp", "In-App Message"),
                            ("notification", "Notification"),
                        ],
                        max_length=12,
                    ),
                ),
                ("subject", models.CharField(max_length=150)),
                ("body", models.TextField()),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("recipients", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("sent", "Sent")],
                        default="draft",
                        max_length=6,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("body", models.TextField(blank=True, max_length=2000)),
                ("link", models.CharField(blank=True, max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("read", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_no",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("payer_name", models.CharField(max_length=100)),
                ("payer_phone", models.CharField(blank=True, max_length=20)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("premium", "Premium plan"),
                            ("advert", "Advert listing"),
                            ("event", "Event registration"),
                            ("membership", "Membership fee"),
                            ("other", "Other"),
                        ],
                        default="premium",
                        max_length=12,
                    ),
                ),
                ("months", models.PositiveSmallIntegerField(default=1)),
                ("description", models.CharField(blank=True, max_length=160)),
                ("amount", models.PositiveIntegerField()),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("mpesa", "M-Pesa"),
                            ("mixx", "Mixx by Yas"),
                            ("airtel", "Airtel Money"),
                            ("selcom", "Selcom"),
                            ("pesapal", "Pesapal"),
                            ("dpo", "DPO"),
                            ("card", "Visa / Mastercard"),
                            ("paypal", "PayPal"),
                            ("bank", "Bank transfer"),
                            ("cash", "Cash"),
                        ],
                        default="mpesa",
                        max_length=10,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Transaction / receipt number from the gateway",
                        max_length=60,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="completed",
                        max_length=10,
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.plan",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "-pk"],
            },
        ),
    ]
