# Generated by Django 6.1.2 on 2026-10-10 00:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_payments_notifications"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="capacity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of seats. Leave blank for no limit.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Comma separated, e.g. Seminar, Education",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="allow_messages_from",
            field=models.CharField(
                choices=[
                    ("all", "All Members"),
                    ("verified", "Verified Members Only"),
                    ("matched", "Matched Members Only"),
                ],
                default="all",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="headline",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="member",
            name="interests",
            field=models.CharField(
                blank=True,
                help_text="Comma separated, e.g. Qur'an, Travel, Reading",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="lifestyle",
            field=models.CharField(
                blank=True,
                help_text="Comma separated, e.g. Healthy lifestyle, Open-minded",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="likes_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="location_display",
            field=models.CharField(
                choices=[("city", "City/Region Only"), ("country", "Country Only")],
                default="city",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="notify_events",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="member",
            name="notify_likes",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="member",
            name="notify_matches",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="member",
            name="notify_messages",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="member",
            name="notify_system",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="member",
            name="photo_visibility",
            field=models.CharField(
                choices=[
                    ("all", "All Members"),
                    ("verified", "Verified Members Only"),
                    ("premium", "Premium Members Only"),
                ],
                default="all",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="practice",
            field=models.CharField(
                choices=[
                    ("practising", "Practising"),
                    ("moderate", "Moderately practising"),
                    ("learning", "Learning / revert"),
                ],
                default="practising",
                max_length=12,
                verbose_name="Religiosity",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="profile_visibility",
            field=models.CharField(
                choices=[
                    ("all", "All Members"),
                    ("verified", "Verified Members Only"),
                    ("premium", "Premium Members Only"),
                    ("hidden", "Hidden"),
                ],
                default="all",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="show_age",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="member",
            name="show_in_search",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="member",
            name="show_online",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="member",
            name="ui_language",
            field=models.CharField(
                choices=[("en", "English"), ("sw", "Kiswahili")],
                default="en",
                max_length=2,
                verbose_name="Language",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="ui_theme",
            field=models.CharField(
                choices=[("light", "Light Mode"), ("dark", "Dark Mode")],
                default="light",
                max_length=5,
                verbose_name="Theme",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="image",
            field=models.ImageField(blank=True, upload_to="messages/"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="payment_instructions",
            field=models.TextField(
                blank=True,
                default="Lipa kwa M-Pesa, Mixx by Yas au Airtel Money, kisha weka namba ya muamala (transaction reference) hapa chini. Tutathibitisha malipo na kuwasha mpango wako.",
                help_text="Shown to members on the Membership page when they upgrade, e.g. your Lipa Namba / till number.",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.CreateModel(
            name="ProfileView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_views",
                        to="core.member",
                    ),
                ),
                (
                    "viewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_views_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.CharField(max_length=200)),
                ("results", models.PositiveIntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("contact", "Message to support"),
                            ("ticket", "Technical ticket"),
                            ("report", "Report an issue"),
                            ("verification", "Verification request"),
                            ("feedback", "Feedback"),
                            ("discount", "Discount code"),
                            ("chat", "Live chat request"),
                        ],
                        default="contact",
                        max_length=12,
                    ),
                ),
                ("subject", models.CharField(max_length=150)),
                ("message", models.TextField(max_length=3000)),
                ("attachment", models.FileField(blank=True, upload_to="support/")),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=6,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_by",
                        to="core.member",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "member"), name="unique_block"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ConversationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("favorite", models.BooleanField(default=False)),
                ("archived", models.BooleanField(default=False)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.member",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "member"), name="unique_conversation_state"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EventSave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saves",
                        to="core.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "event"), name="unique_event_save"
                    )
                ],
            },
        ),
    ]
