from django.urls import path
from . import views
urlpatterns = [
    path("", views.dashboard, name="m_dashboard"),
    path("find/", views.find, name="m_find"),
    path("matches/", views.matches, name="m_matches"),
    path("messages/", views.messages_page, name="m_messages"),
    path("messages/<int:pk>/", views.messages_page, name="m_messages_with"),
    path("messages/<int:pk>/action/", views.conversation_action, name="m_convo_action"),
    path("profile/", views.profile, name="m_profile"),
    path("profile/edit/", views.profile_edit, name="m_profile_edit"),
    path("profile/photos/", views.photos, name="m_photos"),
    path("profile/photos/main/", views.photo_action, name="m_photo_main"),
    path("profile/photos/<int:pk>/", views.photo_action, name="m_photo_action"),
    path("profile/preferences/", views.preferences, name="m_prefs"),
    path("profile/verification/", views.verification, name="m_verify"),
    path("profile/visibility/", views.visibility, name="m_visibility"),
    path("views/", views.views, name="m_views"),
    path("liked/", views.liked, name="m_liked"),
    path("activity/", views.activity, name="m_activity"),
    path("events/", views.events, name="m_events"),
    path("events/<int:pk>/", views.event_detail, name="m_event"),
    path("events/<int:pk>/save/", views.event_save, name="m_event_save"),
    path("membership/", views.membership, name="m_membership"),
    path("membership/receipt/<int:pk>/", views.receipt, name="m_receipt"),
    path("safety/", views.safety, name="m_safety"),
    path("block/<int:pk>/", views.block, name="m_block"),
    path("settings/", views.settings_page, name="m_settings"),
    path("settings/password/", views.password, name="m_password"),
    path("settings/sessions/", views.end_sessions, name="m_sessions"),
    path("settings/export/", views.export, name="m_export"),
    path("settings/deactivate/", views.deactivate, name="m_deactivate"),
    path("settings/delete/", views.delete_account, name="m_delete"),
    path("help/", views.help_page, name="m_help"),
    path("notifications/", views.notifications, name="m_notifications"),
]
